### ISSUE TITLE
Kasten backup issue on Openshift

### ISSUE THREAD

**Issue by Sg-23** [kanisterio/kanister#1088]
I am facing issue while creating a backup of pv on Openshift cluster v4.6.29 using Kasten.

I am unable to create volume snapshot with the following error in events :
**Waiting for a snapshot test-project/k10-csi-snap-vtmhd4spq2bnc6rt to be created by the CSI driver.**

The provisioner for the pv is rook-ceph.rbd.csi.ceph.com. 

I have installed kasten using Helm [https://docs.kasten.io/latest/install/openshift/helm.html]

**Comment by pavannd1** [comment]
Hi @Sg-23, this looks like an issue related to Kasten K10 - please send an email to support@kasten.io for further assistance.
