### ISSUE TITLE
kanister bins are working only inside alpine image

### ISSUE THREAD

**Issue by depohmel** [kanisterio/kanister#110]
I faced an issue running kando inside Debian based image
and digging further found this one: https://github.com/rust-lang/rust/issues/40049

ldd from alpine
```
22cf735ce9ad:/# ldd $(which kando)
	/lib/ld-musl-x86_64.so.1 (0x7fe89c655000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fe89c655000)
```

ldd from debian:
```
root@c684e1008dc1:/# ldd /usr/local/bin/kando
	linux-vdso.so.1 (0x00007ffebfbfe000)
	libc.musl-x86_64.so.1 => not found
```

as a workaround, i  installed musl-dev on Debian.

**Comment by SupriyaKasten** [comment]
Fixed! [#3541](https://github.com/kastenhq/k10/pull/3541#event-1775655368)
