### ISSUE TITLE
May I request to support PostgreSQL 14+?

### ISSUE THREAD

**Issue by terry5168** [kanisterio/kanister#1131]
Currently, 0.6.9 only support PostgreSQL 13.3- version. Doesn't work for 14.0+ DB backup/restore.

Much appreciate if update the PostgreSQL image for 14.0+

Upgrade image ghcr.io/kanisterio/postgres-kanister-tools:0.69.0 with latest PostgreSQL client shipped.

BTW: How to change the timezone of dest file?
pg_backups/{{ .StatefulSet.Namespace }}/{{ .StatefulSet.Name }}/{{ **toDate "2006-01-02T15:04:05.999999999Z07:00" .Time | date "2006-01-02T15:04:05Z07:00"** }}/backup.sql.gz 

Such as , change from UTC to GMT+5. 

 
Thanks!

**Comment by A-kanksh-a** [comment]
> BTW: How to change the timezone of dest file?
> pg_backups/{{ .StatefulSet.Namespace }}/{{ .StatefulSet.Name }}/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time | date "2006-01-02T15:04:05Z07:00" }}/backup.sql.gz
> 
> Such as , change from UTC to GMT+5.

Hey @terry5168 you can refer this [https://docs.kanister.io/templates.html#time](https://docs.kanister.io/templates.html#time)

**Comment by terry5168** [comment]
Thanks for the reply. 
Ya, I checked that doct. But seems not get the trick.
I tried to change timezone by changing:
 "2006-01-02T15:04:05.999999999+08:00" .Time  | date "2006-01-02T15:04PM"
the result as following:  
/mongodb-backups/ota-mongodb/**0001-01-01T00:00AM**/mongodb_backup.gz
the date seems messed and time is wrong.

**Comment by terry5168** [comment]
https://github.com/kanisterio/kanister/blob/master/docker/postgresql/Dockerfile
