### ISSUE TITLE
[BUG] seems Cassandra blueprint doesn't work at all

### ISSUE THREAD

**Issue by terry5168** [kanisterio/kanister#1132]
Cassandra DB backup blueprint doesn't work!

create the blueprint.
create backup actionset.
error messages as following:

time="2021-11-09T03:48:53.060540302Z" level=info msg="Pod Update" Container=cassandra File=pkg/format/format.go Function=github.com/kanisterio/kanister/pkg/format.info Line=55 Out="+ echo 'shasum is required'" Pod=data-cassandra-848f7b6c97-pl96z cluster_name=b655c56f-8039-4584-86ab-7b3af679936d hostname=kanister-operator-679bdd8c5b-5zs2x
time="2021-11-09T03:48:53.060556204Z" level=info msg="Pod Update" Container=cassandra File=pkg/format/format.go Function=github.com/kanisterio/kanister/pkg/format.info Line=55 Out="+ exit 1" Pod=data-cassandra-848f7b6c97-pl96z cluster_name=b655c56f-8039-4584-86ab-7b3af679936d hostname=kanister-operator-679bdd8c5b-5zs2x
time="2021-11-09T03:48:53.071883812Z" level=info msg="Failed to execute phase: v1alpha1.Phase{Name:\"getBackupPrefixLocation\", State:\"pending\", Output:map[string]interface {}(nil)}:" ActionSet=backup-vksjm File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).runAction.func1" Line=438 Phase=getBackupPrefixLocation cluster_name=b655c56f-8039-4584-86ab-7b3af679936d error="command terminated with exit code 1" hostname=kanister-operator-679bdd8c5b-5zs2x
time="2021-11-09T03:48:53.072393294Z" level=info msg="Updated ActionSet" Actionset=backup-vksjm File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onUpdateActionSet" Line=227 Status=failed cluster_name=b655c56f-8039-4584-86ab-7b3af679936d hostname=kanister-operator-679bdd8c5b-5zs2x

**Comment by terry5168** [comment]
Comments: It doesn't work for my existing deployment  cassandra instance backup.

**Comment by A-kanksh-a** [comment]
hi @terry5168, could you please provide some more details on how the Cassandra instance is deployed on your machine?

**Comment by terry5168** [comment]
Sorry for the late response, it deployed as Deployment. We created the Helm chart manually.
