### ISSUE TITLE
[BUG] make install-minio fails sometimes because of resource issues

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1176]
**Describe the bug**
To test the integrations tests when as a prerequisite when we run `make install-minio` it sometimes fails because of the resource requirement of minio deployment.
It, I think, by default requests 5G which might not be available on some of the clusters. We should try to install minio with lesser resource request, if their helm chart provides this.

**To Reproduce**

Run `make install-minio` it fails sometimes.

**Expected behavior**
Minio should be installed successfully.

**Comment by ihcsim** [comment]
The default persistence size is actually 500Gi! We should make this to 2GiB, make it configurable in `bin/minio.sh`.

```
$ helm show values minio/minio --jsonpath='{.persistence.size}'                                                          
500Gi%                   
```
