### ISSUE TITLE
Enhance CreateVolumeSnapshot function to snapshot vSphere CSI 2.4.0 Alpha volumes

### ISSUE THREAD

**Issue by ron1** [kanisterio/kanister#1201]
**Is your feature request related to a problem? Please describe.**
Use CreateVolumeSnapshot function to snapshot vSphere CSI 2.4.0 Alpha volumes

**Describe the solution you'd like**
CreateVolumeSnapshot function creates snapshots for vSphere CSI 2.4.0 Alpha volumes

**Describe alternatives you've considered**

**Environment**
Kubernetes Version/Provider: Rancher RKE2 1.21.5-rke2r1
Storage Provider: vSphere
Cluster Size (#nodes): 6

**Additional context**

**Comment by ihcsim** [comment]
@ron1 If these snapshots are done through the [CSI `VolumeSnapshot` APIs](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-E0B41C69-7EEB-450F-A73D-5FD2FF39E891.html), you should be able to do it with the [`CreateCSISnapshot`](https://docs.kanister.io/functions.html#createcsisnapshot) and the [`CreateCSISnapshotStatic`](https://docs.kanister.io/functions.html#createcsisnapshotstatic) functions.

**Comment by ron1** [comment]
Thanks
