### ISSUE TITLE
Document how to schedule an actionset via k8s cron job

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1209]
**Is your feature request related to a problem? Please describe.**
Per current implementation, an action from a blueprint can only be run/triggered by creating the actionset manually. There should be a way to trigger the actions from blueprint periodically.

**Describe the solution you'd like**
There should be a way to run those actionsets periodically maybe by using Kubernetes Cron Jobs.

**Comment by nicolas-g** [comment]
👍

**Comment by theangryangel** [comment]
Sorry for the noise. This is largely a new comment to mark as non-stale.

I realise there’s probably a fair amount of overlap between this feature request and I guess k10?

ultimately is a cron that calls kubectl to create an action set what we’re looking for here?

**Comment by viveksinghggits** [comment]
That's right @theangryangel. The job is just going to create the actionset resource behind the scenes and overlap with K10 were the reasons why we were not actively looking into this. But I will make sure to bump it up on the community meeting. Does that sound good?

**Comment by ihcsim** [comment]
The overlap is insignificant. Kanister gears towards users with K8s experience and RBAC permissions to create their own `CronJob` workloads. K10 comes with built-in scheduled job feature (backed up Kasten's support) which abstracts away the underlying K8s workload APIs from the users.

**Comment by ihcsim** [comment]
Still relevant. See #1566.

**Comment by ihcsim** [comment]
Resolved by #1566.

**Comment by onedr0p** [comment]
@ihcsim unfortunately not everyone uses ArgoCD, and even still it isn't the only GitOps tool for Kubernetes. A more generic example would be better IMO.

**Comment by ihcsim** [comment]
@onedr0p I see your point. We decided to start with a tutorial involving Argo Workflows to show how Kanister can be integrated seamlessly with other cloud native workflow orchestration tools. Looks like we still have some work to do. 

Will you be interested in collaborating on a pull request to extend the tutorial to include a section to use the CronJob API? It will give us a better understanding of your use case. Many of the items described in the Argo Workflows (namespacing, RBAC permissions etc.) are still relevant, even when using CronJob.

**Comment by wesjdj** [comment]
We have a bit of documentation and an example of a backup cronjob in the [Taweret](https://github.com/SwissDataScienceCenter/taweret#backup-cronjob) docs
