### ISSUE TITLE
Support to have an eventual phase that can be run at the end of every action

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1221]
### Discussed in https://github.com/kanisterio/kanister/discussions/1220

<div type='discussions-op-text'>

<sup>Originally posted by **viveksinghggits** February  4, 2022</sup>
@glothriel, was kind enough give this feedback to have an eventual phase for every action to make sure we are able to cleanup the resources if they were created in previous phases.
I am creating this thread to continue the discussion and if you have any other ideas around it and then we can add this to the roadmap.

- [ ] Eventual phase should be called after all the phases of an action are called
- [ ] It should be called irrespective of the status of previous phases</div>

**Comment by ihcsim** [comment]
Completed in https://github.com/kanisterio/kanister/pull/1297.
