### ISSUE TITLE
Kanister CRDs should be distributed with helm chart

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1243]
### Discussed in https://github.com/kanisterio/kanister/discussions/1232

<div type='discussions-op-text'>

<sup>Originally posted by **viveksinghggits** February  7, 2022</sup>
Kanister CRDs right now are distributed with kanister controller code and not the helm chart. Ideally we should try to distribute them with helm chart. 
In some scenarios people were not able to upgrade to newer version because they didn't want to give kanister access to manage CRDs and because of that upgrade to recent version failed.</div>

**Comment by pavannd1** [comment]
@viveksinghggits We should probably add something to the docs too

**Comment by viveksinghggits** [comment]
right, I will do that. thanks @pavannd1 .

**Comment by viveksinghggits** [comment]
https://github.com/kanisterio/kanister/pull/1278
