### ISSUE TITLE
Makefile should have targets to just build the binaries and maybe to build separate one as well

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1250]
**Describe the solution you'd like**
Makefile, right now doesn't support targets to just build the binaries or build one binary. I think we should have Makefile targets that enable us to do that.

**Describe alternatives you've considered**
Commenting things from `.goreleaser` file to just build the things that we want.

**Comment by ihcsim** [comment]
This already works per changes in #1355.

```
make build ARCH=amd64 BIN=controller

make build ARCH=amd64 BIN=kanctl

make build ARCH=amd64 BIN=kando
```
