### ISSUE TITLE
`make check` command to check if dependencies needed to build the project are installed.

### ISSUE THREAD

**Issue by alisondy** [kanisterio/kanister#1266]
I would like a make check command to see if I have the appropriate dependencies installed.

If this exists already, please refer me to the appropriate documentation and close this issue.

**Comment by ihcsim** [comment]
AFAICT, we don't have this. At the minimum, `check` should confirm the presence and version of `go`, `git`, `docker`, `golangci-lint` and `kubectl`, for development tasks. We have some shell scripts that use `kind`, `minikube`, `helm` etc. - I think these should be optional. And `goreleaser` and `aws` are needed only for releases.
