### ISSUE TITLE
Add optional argument "wait" to ScaleWorkload

### ISSUE THREAD

**Issue by muffl0n** [kanisterio/kanister#1290]
We have a rather complex setup that has many different deployments/statefulset that need to be stopped and started in order. Some components take a rather long time to scale up, so that blocks the execution of restore and backup.
For some components, there is no sense in waiting for them to scale up.

**Describe the solution you'd like**
I'd love to have an optional argument "wait" for the function "ScaleWorkload" that allow me to set it to "false". So that the function does not wait for the pods to be started completely.

**Describe alternatives you've considered**
I've considered scaling up the workload in a KubeTask.

**Additional context**
I already found the two functions, that do the scaleup and the mentioned wait. But I'm too bad at Go to implement this feature, yet.
https://github.com/kanisterio/kanister/blob/e495125eac68d4eb209b22c7f32f7c94b9477058/pkg/kube/workload.go#L360-L384

**Comment by pavannd1** [comment]
@kale-amruta Please take a look at this one. Thank you!

**Comment by muffl0n** [comment]
Awesome! Thank you very much! Can't wait to give it a try.
