### ISSUE TITLE
[BUG] Can't apply blueprint cause webhook can't be reached

### ISSUE THREAD

**Issue by muffl0n** [kanisterio/kanister#1292]
**Describe the bug**
When I try to apply a blueprint, I get this error message
```
Error from server (InternalError): error when creating "blueprint.yaml": Internal error occurred: failed calling webhook "blueprints.cr.kanister.io": failed to call webhook: Post "https://kanister-kanister-operator.kanister.svc:443/validate/v1alpha1/blueprint?timeout=5s": context deadline exceeded
```

**To Reproduce**
1. Create blueprint.yaml 
2. Call `kubectl apply -f blueprint.yaml`
3. Get error message

**Expected behavior**
Blueprint should be applied without an error.

**Environment**
Kubernetes Version/Provider: GKE v1.22.6-gke.300
Helm-Chart: 0.74.0
Kanister operator: Develop version of PR #1282

Though I'm using the develop version of said PR, I can also reproduce this behaviour with released version ghcr.io/kanisterio/controller:0.74.0

**Comment by viveksinghggits** [comment]
Hi @muffl0n, 
can you please confirm if you are facing this continuously or this is intermittent.

**Comment by muffl0n** [comment]
I can reproduce this on every try.

**Comment by ihcsim** [comment]
Are there any relevant logs in the operator?

**Comment by muffl0n** [comment]
None I found so far. Is there any method to pump up the logging?

**Comment by ihcsim** [comment]
Should be able to use the `LOG_LEVEL` env var to set the log level. See supported values [here](https://github.com/kanisterio/kanister/blob/e495125eac68d4eb209b22c7f32f7c94b9477058/pkg/log/log.go#L23-L32).

**Comment by ihcsim** [comment]
9443 is the default port used in the [`webhook` package](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.1/pkg/webhook#pkg-variables). Also, it might have something to do with getting the HTTP server to listen at a lower number port requires the `NET_ADMIN` capability.
