### ISSUE TITLE
Add example to perform backup and restore on Minio

### ISSUE THREAD

**Issue by shlokchaudhari9** [kanisterio/kanister#1323]
**Is your feature request related to a problem? Please describe.**

An example that demonstrates Kanister's ability to protect application data on Minio

**Additional context**

[Existing examples](https://github.com/kanisterio/kanister/tree/master/examples) can be referred to document the use-case

**Comment by aland-zhang** [comment]
kanctl create profile s3compliant --access-key admin --secret-key adminadmin --bucket backup --region us-east-1 --endpoint http://10.43.24.100:9000 --namespace kanister 
secret 's3-secret-iohsc6' created
Failed the 'Validate bucket region specified in profile' check.. ❌
validation failed, deleting secret 's3-secret-iohsc6'
secret 's3-secret-iohsc6' deleted
Error: profile validation failed: failed to get bucket backup: GetBucketLocation: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
        status code: 403, request id: RRZQ3HV3SQ8GWP7T, host id: 8L8tyY553VdlDMNeN1SKJBK5kXw80t780aLTYvoX4DPxsSHTiyPhpFPr+WiTVDbdJc31rXiv36Y=

**Comment by ihcsim** [comment]
@aland-zhang See https://github.com/kanisterio/kanister/issues/682#issuecomment-1141240149.
