### ISSUE TITLE
Support for GKE Workload Identity

### ISSUE THREAD

**Issue by nicolas-g** [kanisterio/kanister#1324]
**Is your feature request related to a problem? Please describe.**

Right now I only see the option to create secrets manually that needs to be added to the Profile.
Creating secrets is not a good practice since they can expire and require manual rotation.

**Describe the solution you'd like**
Will be great if Kanister can support GKE workload identity.

https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Environment**
Storage Provider: GCP/GCS

**Additional context**
This is similar to AWS [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), or 'IAM Roles for Service Accounts'  which I also think is not by supported Kanister but correct me if I'm wrong.

**Comment by ihcsim** [comment]
@nicolas-g Sorry for the late response. AIUI, to get Kanister to work with Workload Identity, it's just a matter of annotating the Kanister's service account with your IAM service account, right? We recently merged https://github.com/kanisterio/kanister/pull/1248 that let you do that. PTAL to see if that resolves your issue. Thanks.

**Comment by ngeorgakopoulos-deloitte** [comment]
I will give it a try as soon as I can, @ihcsim thank you for getting back to me.
