### ISSUE TITLE
Make sure we are not using duplicate shorthand flags for our CLIs

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1336]
Thanks for the fix :+1:! 

> I still see some other instances of same characters being used as shorthand flag.

Can we create a bug issue to track those? Thanks.

_Originally posted by @ihcsim in https://github.com/kanisterio/kanister/pull/1334#pullrequestreview-923563144_

**Comment by pavannd1** [comment]
🚀

**Comment by hairyhum** [comment]
I've checked the commands we have right now in `kanctl` and `kando`. Don't see any overlap for shorthands between global and subcommand flags. We still user same shorthands in different commands, but I think it's not a problem as long as they're not subcommands.

**Comment by viveksinghggits** [comment]
> I've checked the commands we have right now in `kanctl` and `kando`. Don't see any overlap for shorthands between global and subcommand flags. We still user same shorthands in different commands, but I think it's not a problem as long as they're not subcommands.

Hi @hairyhum ,
Thank you for verifying. If we are sure that we don't have this problem anymore, let's close this issue.
