### ISSUE TITLE
CRD API Versioning

### ISSUE THREAD

**Issue by ihcsim** [kanisterio/kanister#1349]
Devise a version management plan for the Kanister CRDs to reflect their stability. Ideally, an update like https://github.com/kanisterio/kanister/pull/1297 should be reflected by a new version of the CRD e.g., `v1alpha2`. We need to understand the change scope of a version bump, and what would a version migration path looks like for the community.

Some questions:

* When is it necessary to bump the version?
* Do we want to support multiple versions? If yes, how far back?
* When introducing new "major" versions upgrade, what does the conversion strategy between old internal storage version and the new API versions look like?
    * Tooling for user to enable migration path
    * Migration of stored object using https://github.com/kubernetes-sigs/kube-storage-version-migrator
* What is our version deprecation strategy?

**Comment by pavannd1** [comment]
Valid 🚀
