### ISSUE TITLE
CockroachDB Blueprint

### ISSUE THREAD

**Issue by MichaelCade** [kanisterio/kanister#1361]
**Is your feature request related to a problem? Please describe.**
Had a request now twice around being able to protect CockroachDB with a Kanister blueprint.

**Describe the solution you'd like**
Explore native capabilities within CockroachDB and the ability to use a Kanister blueprint to export backups > to then create a Blueprint to enable the data protection of CockroachDB

**Comment by pavannd1** [comment]
Valid 🚀

**Comment by ihcsim** [comment]
See #1585.
