### ISSUE TITLE
GCP/GCS Error: profile validation failed to get bucket gs://"mongodb-bucket" not found

### ISSUE THREAD

**Issue by ngeorgakopoulos-deloitte** [kanisterio/kanister#1374]
**Describe the bug**

We have created a Service Account for kanister with `roles/storage.objectAdmin` to gcs `xyz123456-mongodb-backup` bucket.

Using the service account from the command line we can confirm that we have access to the above bucket uploading and deleting files. 

However when we use the same service account keys to create a profile, the profile check fails with an error message that the bucket has not been found.

**To Reproduce**
```
kanctl create profile gcp --bucket gs://xyz123456-mongodb-backup --region us-east1 --project-id ${GCP_PROJECT_ID} --service-key kanister-backups-service-acct.json -n mongodb --verbose
```

Output:
```
secret 'gcp-secret-g65baq' created
Failed the 'Validate bucket region specified in profile' check.. ❌
validation failed, deleting secret 'gcp-secret-g65baq'
secret 'gcp-secret-g65baq' deleted
Error: profile validation failed: failed to get bucket gs://xyz123456-mongodb-backup: not found
{"File":"cmd/kanctl/main.go","Function":"main.main","Line":28,"error":"profile validation failed: failed to get bucket gs://xyz123456-mongodb-backup: not found","level":"info","msg":"Kanctl failed to execute","time":"2022-04-08T11:11:43.246688-04:00"}
```

**Expected behavior**
gcp-secret and profile resource to have been created successfully 

**Environment**
Kubernetes Version/Provider:  Server Version: v1.20.15-gke.1000
Storage Provider:  GCS
Cluster Size (#nodes): 2
Data Size: NA

**Comment by ihcsim** [comment]
@ngeorgakopoulos-deloitte thanks for filing the issue. Can you try with just the bucket name i.e. `--bucket xyz123456-mongodb-backup`? The `kanctl` code eventually calls into the upstream [SDK](https://pkg.go.dev/google.golang.org/api/storage/v1#BucketsGetCall.Do).

**Comment by nicolas-g** [comment]
Hi @ihcsim , I tried removing the `gs://` and it has the same result.

**Comment by nicolas-g** [comment]
hi @ihcsim , I'm only using `roles/storage.objectAdmin`, it seems you are also `roles/storage.admin`...
I assume if you are using roles/storage.admin` you don't need `roles/storage.objectAdmin`

**Comment by ihcsim** [comment]
When I assigned the role via the console, it auto-assigns `roles/storage.admin` even when I only picked `roles/storage.objectAdmin`. Would `roles/storage.admin` make a difference?

**Comment by nicolas-g** [comment]
@ihcsim I'm not sure as I don't have admin access in our current environment, I will try to find out and let you know thanks for the help.

**Comment by muffl0n** [comment]
Like mentioned in [Slack](https://kanisterio.slack.com/archives/C85C8V22J/p1649433608494049?thread_ts=1648572583.629159&cid=C85C8V22J) you probably need the right `storage.buckets.get` for that bucket cause the underlying lib (stow) does a "Get()" on that bucket. And `roles/storage.objectAdmin` does not include that permission. Please check your GCP-logs, it should show you the violation.
Also, it *should* be sufficient to get `roles/storage.admin` on the bucket. No need to get it for the whole project.

There also seems to be a a [change](https://github.com/graymeta/stow/commit/49bd11e2c7af808b1599b732f1b58a21694c303b#diff-f83079c3fa8cdcce3a69d5e83f546fe4e1a3954bae2d1b2cb4897c710801d057L30) in version v0.2.7 of stow, that does not use `Get()` on the bucket anymore. Kanister currently uses a patched v0.2.6.

**Comment by nicolas-g** [comment]
@muffl0n @ihcsim it seems all we need is to only use `roles/storage.admin` role, I can see backups now been created.

Thank you for your help, we can close this issue.

**Comment by nicolas-g** [comment]
Please add this to your documentation for GCP, it would have save a lot of time for everyone .

**Comment by ihcsim** [comment]
@nicolas-g How do you feel about helping us to update the documentation, in exchange for some open source fame and glory :wink:? We are also putting together some swags for contributors. If interested, the [troubleshooting guide](https://github.com/kanisterio/kanister/blob/master/docs/troubleshooting.rst) feels like the best place for it.

**Comment by nicolas-g** [comment]
if my time allowes it I mght submit a PR :)

I don't think this should be part of the trbouleshooting guide, we should have a document quide of the setup and requiremetns for each Cloud Provider to begin (create bucket/ServiceAccont/Permissinos etc..).

**Comment by ihcsim** [comment]
Closing this issue, per https://github.com/kanisterio/kanister/issues/1374#issuecomment-1097260130. Feel free to re-open it if necessary.
