### ISSUE TITLE
comparison to other tools

### ISSUE THREAD

**Issue by geekflyer** [kanisterio/kanister#138]
Hi,

just stumpled by chance upon kanister and scratched it's documentation.
While doing so I was asking myself a couple of times how kanister fits in with other tools.
Particularly it looks to me kanister has quite some overlap with kubedb and argo (it does a bit of both).
Could you clarify - perhaps in the readme - how kanister compares to such tools?

**Comment by vkamra** [comment]
@geekflyer - thanks for checking Kanister out! I think it'll make sense to add this to the README.

The focus of Kanister is data-management operations (think Backup, Restore, Migration, Replication, Data Masking...) and providing the tooling required to express and execute such operations across a variety of applications (see https://docs.kanister.io/functions.html for what already exists with a lot more coming soon!)

When it comes to differences between the projects you mentioned - it comes down to :
(a) Kanister is not a general purpose workflow engine (CI/CD) but focused on data operations 
(b) Kanister aims to work with any/all data services out there that you might be using - not provide a collection of data service stacks out of the box. 

Hope this helps - would love to hear what sparked your interest and if there's a use-case this helps with?

**Comment by geekflyer** [comment]
Ok yeah thanks, I think that helps a bit.
I really just looked at kanister when browsing through the helm github repo and I thought that kanister (because of it's name) might be related to kaniko, that's what sparked my interest - so it was really just random haha.

We're actually using argo since quite some time in my company and recently looked for ways to run (relatively small) instances of mongodb and elasticsearch reliably in kubernetes and are currently evaluating kubedb for it. It sounds that kanister also would help a lot in the latter, although kubedb has already some functionalities for data management built in.
I'll keep kanister in mind, may make use of it very soon :)

**Comment by vkamra** [comment]
Excellent - ping us on [Slack](https://kasten.typeform.com/to/QBcw8T) when you get to it!
