### ISSUE TITLE
[BUG] Failed to connect to the backup repository

### ISSUE THREAD

**Issue by micahosborne** [kanisterio/kanister#1422]
**Describe the bug**
I"m getting an error from k10 when trying to connect to my backup repository (google cloud buckets).  I have added the integration in the app, and it validates, but still get the error below.

**Expected behavior**
If my job will fail, shouldn't validation fail? Also, what could be going wrong here?

cause:
  cause:
    fields:
      - name: FailedSubPhases
        value:
          - Err:
              cause:
                cause:
                  cause:
                    cause:
                      message: command terminated with exit code 1
                    file: kasten.io/k10/kio/kopia/repository.go:549
                    function: kasten.io/k10/kio/kopia.ConnectToKopiaRepository
                    linenumber: 549
                    message: Failed to connect to the backup repository
                  fields:
                    - name: appNamespace
                      value: ns
                  file: kasten.io/k10/kio/exec/phases/phase/export.go:216
                  function: kasten.io/k10/kio/exec/phases/phase.prepareKopiaRepoIfExportingData
                  linenumber: 216
                  message: Failed to create Kopia repository for data export
                file: kasten.io/k10/kio/exec/phases/phase/export.go:138
                function: kasten.io/k10/kio/exec/phases/phase.(*exportRestorePointPhase).Run
                linenumber: 138
                message: Failed to copy artifacts
              fields: []
              message: Job failed to be executed
            ID: cbbdd022-c913-11ec-a5d7-cecf951fd2c4
            Phase: Exporting RestorePoint
    file: kasten.io/k10/kio/exec/phases/phase/queue_and_wait_children.go:185
    function: kasten.io/k10/kio/exec/phases/phase.(*queueAndWaitChildrenPhase).processGroup
    linenumber: 185
    message: Failure in exporting restorepoint
  fields:
    - name: manifestID
      value: 8a9aec2f-c913-11ec-a5d7-cecf951fd2c4
    - name: jobID
      value: 8aa009c7-c913-11ec-b4a4-a6e61638a683
    - name: groupIndex
      value: 0
  file: kasten.io/k10/kio/exec/phases/phase/queue_and_wait_children.go:87
  function: kasten.io/k10/kio/exec/phases/phase.(*queueAndWaitChildrenPhase).Run
  linenumber: 87
  message: Failed checking jobs in group
message: Job failed to be executed
fields: []

**Comment by ihcsim** [comment]
@micahosborne Thanks for bringing this up. This looks like a K10 issue. Can you raise it at https://community.veeam.com/groups/kasten-k10-support-92? I am closing this issue. Feel free to re-open if you suspect it's related to Kanister.
