### ISSUE TITLE
Explore Moving Documentation To GitHub Pages

### ISSUE THREAD

**Issue by ihcsim** [kanisterio/kanister#1436]
We should explore moving the docs site to GitHub Pages. It seems to provide better support for markdown/HTML/CSS/JS and integration with GitHub Actions. Together with Jekyll, it also offer a wide selection of themes.

**Comment by julio-lopez** [comment]
@ihcsim https://github.com/gohugoio/hugo is a good alternative for Jekyll, if not preferred.

**Comment by ihcsim** [comment]
@julio-lopez No complains about Hugo; I used it in a previous project. What does the Hugo/GH Pages integration look like? I haven't looked into it, but GH Pages mentioned Jekyll has [built-in support](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll).

**Comment by pavannd1** [comment]
Still relevant

**Comment by Sagar2366** [comment]
@ihcsim @pavannd1 I would like to work on this issue.

**Comment by ihcsim** [comment]
@Sagar2366 Currently, all the docs are written in [rst](https://docutils.sourceforge.io/rst.html) format. Any idea what does porting it over to GH Pages with Hugo looks like, including CI automation etc.?

**Comment by mlavi** [comment]
https://github.com/kanisterio/kanister/tree/master/docs are published to S3+Cloudfront during Kanister release, from internal Kasten pipeline. Let's discuss refactoring build+publish docs to GitHub.

**Comment by hairyhum** [comment]
https://github.com/kanisterio/kanister/pull/2642 is merged. Now we need to make a GH workflow to build and publish the docs.

**Comment by mlavi** [comment]
While that is underway, I've made REQ0054258 with Veeam CT to update DNS with doc-new IN CNAME kanisterio.github.io
