### ISSUE TITLE
Update k8s.io dependencies to 0.24.x

### ISSUE THREAD

**Issue by julio-lopez** [kanisterio/kanister#1438]
Various k8s dependencies need to be updated in tandem, otherwise building fails. See #1434

**Comment by pavannd1** [comment]
@kale-amruta Please take this one 👍🏼 
We may need an update similar to this one - https://github.com/kanisterio/kanister/pull/1211

**Comment by pavannd1** [comment]
Reopening as the code changes were reverted.
