### ISSUE TITLE
Add support to backup block volumes

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#1451]
**Is your feature request related to a problem? Please describe.**

Block volumes can be mounted to Kubernetes Pod. https://kubernetes.io/blog/2019/03/07/raw-block-volume-support-to-beta/#using-a-raw-block-pvc
There should be a way to backup such volumes with Kanister

**Describe the solution you'd like**

I tried using `CopyDataVolume` for backup. But the mount fails as it is trying to mount the volume as Filesystem.
We can either introduce an argument to set Mount type or Add a new Kanister function to handle block volumes.

**Describe alternatives you've considered**
NA

**Comment by pavannd1** [comment]
@PrasadG193 ☝🏼

**Comment by PrasadG193** [comment]
@pavannd1 We don't have real ask right now but will be relevant in near future
