### ISSUE TITLE
[BUG] Don't dump the entire pod spec in the controller's logs

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1464]
**Describe the bug**
In the cases where we are using  `KubeTask` kanister function (I think should be reproducible with any function that spins up new pod), if the command that we are running there fails we dump the entire pod spec in the controller's logs which is not useful in most of cases. 
Instead of dumping the entire pod spec we should just log the information (specific fields from `pod.Spec`) that we might need from the pod.

**To Reproduce**
1. Use a blueprint that has KubeTask function in it, MySQL for example. And make sure that phase fails (we can add a command that doesn't exist and the phase will fail)
2. Run backup action, you can follow [this readme](https://github.com/kanisterio/kanister/tree/master/examples/mysql) to do that.
3. See the controller's logs and you will see the entire pod spec  dumped in the logs

**Expected behavior**
We should just log the specific fields from pod.Spec that we might need to debug the problem.

**Screenshots**

![image](https://user-images.githubusercontent.com/19333642/172568865-ee07b432-51c7-4eda-b7cd-80bb54aa3e16.png)

**Comment by akankshakumari393** [comment]
@viveksinghggits I agree that adding entire pod spec in the controller's logs which is not useful in most of cases. But it might be useful in the cases where we would want to debug the state of the Pod at the point it failed. Also, I think there is no useful information in the dump string which we would want to filter out.
