### ISSUE TITLE
Error while connecting to kanister.io slack 

### ISSUE THREAD

**Issue by Sagar2366** [kanisterio/kanister#1655]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/kanisterio/kanister/blob/master/CONTRIBUTING.md
2. Click on Slack hyperlink
3. It will redirect to https://github.com/kanisterio/kanister/blob/master/kanisterio.slack.com and show error message as shown in attached screenshot

**Expected behavior**
URL should redirect to slack signup/login

**Screenshots**
<img width="1407" alt="Screenshot 2022-10-01 at 12 12 00 PM" src="https://user-images.githubusercontent.com/26805882/193396531-71b74337-9347-4fed-acdb-06e7313b0cd3.png">

**Comment by PrasadG193** [comment]
Thanks for reporting this @Sagar2366. Do you mind raising the PR against [kanister](https://github.com/kanisterio/kanister) repo? Looks like you have merged the PR into the forked repo.

**Comment by Sagar2366** [comment]
@PrasadG193 here is PR against Kanister repo - https://github.com/kanisterio/kanister/pull/1656.
