### ISSUE TITLE
Azure has switched to using a new SDK

### ISSUE THREAD

**Issue by bathina2** [kanisterio/kanister#1684]
**Is your feature request related to a problem? Please describe.**
The SDK we currently use is deprecated and we should switch to using the new azure SDK. This will take some work since some there are several changes.
Copied from sdk- 
`Deprecated: Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute]([https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide]([https://aka.ms/azsdk/golang/t2/migration](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)) for guidance on upgrading. Refer to our [deprecation policy]([https://azure.github.io/azure-sdk/policies_support.html](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)) for more details.`

**Describe the solution you'd like**
Switch over to using the new azure sdk

**Comment by pavannd1** [comment]
Duplicates https://github.com/kanisterio/kanister/issues/1568.
