### ISSUE TITLE
Automate the steps to update the kanister build image

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#1685]
**Is your feature request related to a problem? Please describe.**
It's actually project improvement, or devX improvement.

**Describe the solution you'd like**
If someone wants to  make some changes in the kanister's build image, there should be a way to automatically build and push the image to ghcr.

**Comment by Kartik-Garg** [comment]
Hi, can I take up this issue?

**Comment by pavannd1** [comment]
Sure @Kartik-Garg 👍🏼
Most of the images are built using goreleaser during CI but IMO, we should update the build image only when the Dockerfile is modified.

**Comment by viveksinghggits** [comment]
Hi @Kartik-Garg,
are you still willing to work on this? Having a separate make target to build and push the image would be ideal.

**Comment by Kartik-Garg** [comment]
@viveksinghggits 
Yes, still working on it, I will be raising a PR this week :)
