### ISSUE TITLE
Add comments on the Kanister resource types fields in types.go

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#1721]
**Is your feature request related to a problem? Please describe.**

Add comments on all the exported fields in the Kanister resource type structs defined in https://github.com/kanisterio/kanister/blob/master/pkg/apis/cr/v1alpha1/types.go

**Describe the solution you'd like**

For better documentation, add comments on the exported fields on Kanister resource types.
This will allow us to use tools like https://github.com/ahmetb/gen-crd-api-reference-docs/ for better documentation.

**Comment by Kartik-Garg** [comment]
@PrasadG193 Hi, can I take it up?

**Comment by Kartik-Garg** [comment]
@PrasadG193 , Created PR https://github.com/kanisterio/kanister/pull/1751 with respect to this issue, do let me know if any changes are required further.
