### ISSUE TITLE
[BUG] Make target `build-controller` fails when used with `amd64` arch 

### ISSUE THREAD

**Issue by akankshakumari393** [kanisterio/kanister#1738]
**Describe the bug**
`make build-controller` fails with error 
```
error cp: cannot stat 'dist/controller_linux_amd64/controller': No such file or directory 
```

**To Reproduce**
Run `make build-controller` from the root directory of the project

**Expected behavior**
With `amd64` arch `_v1` suffix is appended to the arch value after Go 1.18, so the build is now available at `dist/controller_linux_amd64_v1/controller` and not `dist/controller_linux_amd64/controller`

**Screenshots**

**Environment**
Kubernetes Version/Provider: ...
Storage Provider: ...
Cluster Size (#nodes): ...
Data Size: ...

**Additional context**
Reference [why-is-there-a-_v1-suffix-on-amd64-builds](https://goreleaser.com/customization/build/#why-is-there-a-_v1-suffix-on-amd64-builds)

**Comment by PrasadG193** [comment]
Hi @akankshakumari393 ,
could you please check if the `dist` directory already exists in the project root path? If it exists, could you please try cleaning it up and retry?

**Comment by Bhargav-InfraCloud** [comment]
I encountered this issue while checking on another. It appears that from [goreleaser v1.8.0][1] onwards, the term `v1` is added to the binary's path: `dist/controller_linux_amd64/controller` -> `dist/controller_linux_amd64_v1/controller`

Currently, `make build-controller` only looks for `dist/controller_linux_amd64/`, which is causing the issue.

The easy fix is adding `*` in the end to match any directory name. But as per [commit][2] of the same release, goreleaser will allow `v1` thru `v4` in the same pattern. If at all that means more than one version is possible at the same time, I think `make build-controller` should dynamically pick the latest among all instead on hardcoding.

WDYT?

[1]: https://github.com/goreleaser/goreleaser/releases/tag/v1.8.0
[2]: https://github.com/goreleaser/goreleaser/commit/53bbc6546fdc59d10ca7fe478b05201fcf14aa85
