### ISSUE TITLE
[BUG] The progress column in actionset always has value 10.00 even if actionset is complete

### ISSUE THREAD

**Issue by akankshakumari393** [kanisterio/kanister#1759]
**Describe the bug**
The progress column in actionset always has value 10.00 even if actionset is running, failed

**To Reproduce**
Create any Actionset, we would see the progress to be 10.00 always 
```
kubectl get actionset --all-namespaces
NAMESPACE   NAME           PROGRESS   LAST TRANSITION TIME   STATE
kanister    backup-zpk8d   10.00      2022-11-28T13:23:49Z   running
 ```
**Expected behavior**
We should see some progress with increasing values.

**Screenshots**

**Environment**
Kubernetes Version/Provider: ...
Storage Provider: ...
Cluster Size (#nodes): ...
Data Size: ...

**Additional context**

**Comment by murican** [comment]
I've seen the same issue. Just upgradet Kanister yesterday to 0.91.0.
```
kubectl get actionsets.cr.kanister.io -n kanister
NAME                                                          PROGRESS   RUNNING PHASE   LAST TRANSITION TIME   STATE
backup-enough-whale                                            96.15                      2023-05-23T01:13:30Z   complete
backup-staging-up-wahoo                                     83.33                      2023-05-23T02:03:14Z   complete
delete-backup-cluster-server-keen-gibbon-ndt9r     87.50                      2023-05-23T04:11:24Z   complete

```

**Comment by hinricht** [comment]
Still an issue

**Comment by murican** [comment]
In the meantime we've updated to Kanister version 0.99.0 and the progress tracking seems to be fixed. I think we can close this issue. Thank you very much.
