### ISSUE TITLE
[BUG] : Failed to render template 

### ISSUE THREAD

**Issue by JoKeRGreGre** [kanisterio/kanister#1882]
**Describe the bug**
Imposible to restore backup with blueprints.

I create several blueprints on Kasten, one for postgres database and one for elasticsearch dump. The blueprints was take directly from the kanister repo with some changes

https://github.com/kanisterio/kanister/blob/master/examples/elasticsearch/elasticsearch-blueprint.yaml
https://github.com/kanisterio/kanister/blob/master/examples/postgresql/blueprint-v2/postgres-blueprint.yaml

Backup and export works fine but when i try to restore i've this error for postgres : 

```
Failed to render template: "pgBackup" not found
```

And this error with elasticsearch dump : 

```
Failed to render template: "esBackup" not found
```

**To Reproduce**
BackupStep :

```
host_name=<es-host-name>
backup_file_path='es_backup.tgz'
export ESUSER=<es-user-name>
export ESPASSWORD=<es-user-password>
mkdir /es_backup
multielasticdump --direction=dump --limit=10000 --input=https://${ESUSER}:${ESPASSWORD}@${host_name}:9200 --includeType=data --output=/es_backup
tar -zcvf /${backup_file_path} /es_backup 
kando location push --profile '{{ toJson .Profile }}' --path "${backup_file_path}" --output-name "kopiaOutput" /${backup_file_path}
```

Restore Step : 
```
kopia_snap='{{ .ArtifactsIn.esBackup.KopiaSnapshot }}'
echo $kopia_snap
```
**Expected behavior**
Successfull render {{ .ArtifactsIn.someBackup.KopiaSnapshot }}
Successfull Restore data.

**Environment**
Kubernetes version: 1.22.11 ; 1.24.6
Storage Provider: Azure
Cluster Size: 2
Data Size: ~= 1Gb

**Additional context**

ArtifactsIn seem to be null when i try to display his content.

Even if i try to restore with kanctl :

kanctl create actionset --action restore --namespace kanister --blueprint elasticsearch-blueprint.yaml --namespacetargets kanister --profile <valid-azure-profile>

```
message: 'Failed to execute phase: v1alpha1.Phase{Name:"restoreFromStore", State:"pending",
  Output:map[string]interface {}(nil)}: Failed to render template: "esBackup" not
  found'
```

**Comment by viveksinghggits** [comment]
Hi @JoKeRGreGre,
It seems you are seeing this issue while using Kasten's K10. The better place to ask this question would be https://community.veeam.com/groups/kasten-k10-support-92.
