### ISSUE TITLE
Surface ActionSet errors using Status or Events

### ISSUE THREAD

**Issue by vkamra** [kanisterio/kanister#19]
ActionSet controller failures are currently surfaced by marking the ActionSet status `failed`. Detailed information is only available by viewing controller logs.

We should surface detailed error information by adding a error detail field to ActionSet schema and/or using events.

**Comment by vkamra** [comment]
http://blog.kubernetes.io/2018/01/reporting-errors-using-kubernetes-events.html and https://github.com/kubernetes/sample-controller/blob/master/controller.go describes using Kubernetes events

**Comment by ntolia** [comment]
@SupriyaKasten Fixed, right?

**Comment by SupriyaKasten** [comment]
Yes, fixed this one!

**Comment by SupriyaKasten** [comment]
Fixed!
