### ISSUE TITLE
Use context from parent call in pkg/kube/exec.go

### ISSUE THREAD

**Issue by shahpratikr** [kanisterio/kanister#1930]
**Description**

With k8s upgrade to 0.26.1, streaming functions require context with stream options. One such change was needed [here](https://github.com/kanisterio/kanister/pull/1862/files#diff-ed4a87c699d1a88ffed06f62ac9d91d06f6d52eea0a8358ab2dba7e38fc9aa03L150). We need to get this context from a caller function.

**Comment by Bhargav-InfraCloud** [comment]
@shahpratikr I've submitted #1938. Please review.

**Comment by shahpratikr** [comment]
Hey @Bhargav-InfraCloud , thanks for contributing. But this ticket was created to have context from parent function for `return exec.Stream(remotecommand.StreamOptions{` this call in pkg/kube/exec.go. Also, we need to make this change once #1862 this PR is merged.
