### ISSUE TITLE
Sequential Snapshot Backup Solution for Kubernetes StatefulSet Volumes with Kanister

### ISSUE THREAD

**Issue by Laurianti** [kanisterio/kanister#1974]
**Your problem**
I need to backup the volumes attached to the pods of a RabbitMQ StatefulSet on Azure AKS. However, to ensure HA, I need to stop one RabbitMQ node at a time ([As reported in the official documentation](https://www.rabbitmq.com/backup.html#messages-backup)), backup the attached volume, and then restart the node. I would like the backup process to be as automated as possible.

**Desired solution**
I would like Kanister to provide a solution that allows me to backup the volumes attached to the pods of a RabbitMQ StatefulSet on Azure AKS. Specifically, this solution should ensure HA during the backup process and should be able to backup the volumes attached to the pods one at a time, without compromising the availability of the RabbitMQ cluster. The backup process should include the procedure of sequentially stopping and starting RabbitMQ nodes, allowing the backup of the volume attached to one pod at a time.

**Alternatives considered**
Currently, I am using a custom dump to perform the backup, but I would prefer to use a snapshot backup solution.

**Environment**
Kubernetes version/provider: 1.20.7/Azure AKS
Storage provider: Azure Disk
Cluster size (#nodes): 3
Data size: 500 GB

**Additional context**
I am currently using the RabbitMQ Bitnami Chart on an Azure AKS StatefulSet. The current backup process involves creating a custom dump, but I would prefer to use a snapshot backup solution to improve efficiency. It is essential that the backup process does not compromise the HA of the RabbitMQ cluster. An integrated solution provided by Kanister would be very useful, especially if it could include the procedure of sequentially stopping and starting RabbitMQ nodes, allowing the backup of the volume attached to one pod at a time. It could be useful to use Kanister's pre and post hooks to launch the stop and start commands for the RabbitMQ nodes.

**Comment by mlavi** [comment]
Thank you for joining the Kanister community: it is a framework to orchestrate data management operations.

You seem to be asking for a RabbitMQ StatefulSet blueprint+actionset, which would be an exercise to design and test using Kanister's capabilities. We can wait to see if anyone else in the community replies to this issue who might have one to contribute, help, or provide such a service for hire; you could ask on our Slack instance as well.

Have you reviewed the documentation's tutorial and the example blueprints in this repository? Is there any work there you could adapt and add your current process to? My brief review didn't turn up anything directly relatable, but we'll review this request again with the team and remove the triage label once done.

Please let us know if there is a missing capability in Kanister's functionality that you would need or anything we can improve. We would welcome a contribution via a pull request with your blueprint if you get an example working!

**Comment by viveksinghggits** [comment]
> Is it possible to take snapshots of volumes associated with pods sequentially during the backup process using your platform?

Hi @Laurianti,
First of all sorry for the delay in response.
By snapshot of volumes if you mean, Kubernetes volume snapshots, yes you can take sequential volume snapshots  of the volumes referred by a workload. The kanister function https://docs.kanister.io/functions.html#createcsisnapshot can be used to do the same.
If blueprint is not going to be very dynamic, basically for an action (`backup`) you will have to have `n` phases for `n` volumes referred by your workload.
And those phases are going to be run sequentially. Please feel free to let us know if you need any other help with something else.
