### ISSUE TITLE
`kube.Exec` and `podCommandExecutor.Exec` should create the `ExecOptions` similarly

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#2066]
**Describe the bug**
Right now in Kanister we have two wait to execute command in a pod. 

Create a pod and execute a command into it  (podCommandExecutor)

Execute a command into a running pod

Both of these ways eventually call kube.ExecWithOptions but the ExecOptions that they are called with using these ways are different. 

We should change this behaviour to make sure we are creating the ExecOptions struct in the similar fashion.

**Comment by viveksinghggits** [comment]
cc @e-sumin @pavannd1

**Comment by viveksinghggits** [comment]
@e-sumin can this be closed?

**Comment by e-sumin** [comment]
Not yet, PR will be today or tomorrow. Thanks for keeping an eye.
