### ISSUE TITLE
[BUG] Missing repo-server-controller container

### ISSUE THREAD

**Issue by fastlorenzo** [kanisterio/kanister#2139]
**Describe the bug**

The `repo-server-controller` container is missing from the ghcr.io repository.

**To Reproduce**

Set in the Helm chart values to deploy the repository server controller:
```
repositoryServerController:
      enabled: true
```

**Expected behavior**

The repository server controller should be deployed.

**Screenshots**

```
kanister      0s          Warning   Failed                           pod/kanister-kanister-operator-868b4c5569-6ewisd               Failed to pull image "ghcr.io/kanisterio/repo-server-controller:0.92.0": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/kanisterio/repo-server-controller:0.92.0": failed to resolve reference "ghcr.io/kanisterio/repo-server-controller:0.92.0": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akanisterio%2Frepo-server-controller%3Apull&service=ghcr.io: 401 Unauthorized
```

**Environment**
Kubernetes Version/Provider: v1.27.2+rke2r1 
Storage Provider: NFS
Cluster Size (#nodes): 3
Data Size: N/A

**Additional context**

N/A

**Comment by viveksinghggits** [comment]
Hi @fastlorenzo,
This issues should have been resolved by now. If you try again, I don't think you would get into this problem.

**Comment by fastlorenzo** [comment]
thanks, let me try the latest version and revert back to you shortly

**Comment by fastlorenzo** [comment]
Looks like it's fixed @viveksinghggits , thanks!
