### ISSUE TITLE
Add more linters to golangci.yaml

### ISSUE THREAD

**Issue by kale-amruta** [kanisterio/kanister#2173]
**Is your feature request related to a problem? Please describe.**
Currently `.golangci.yaml` has only following linters enabled:
    - gofmt
    - whitespace
    - gocognit
    - unparam

We should consider adding few more linters that would have enable developers to have better coding standards as well as speed up development and code reviews

**Describe the solution you'd like**
Following linters could be enabled in the golangci

- [gci](https://github.com/daixiang0/gci) - To group imports according to the requirements
- [goheader](https://github.com/denis-tingaikin/go-header) - To add licence headers to the go files
- [stylecheck](https://staticcheck.dev/docs/checks/#S1028) - To check if error messages are not be capitalized.
- [importas](https://github.com/julz/importas) - Create alias for k8s imports in go
- https://github.com/alexkohler/nakedret
- https://github.com/mgechev/revive

**Comment by ankitjain235** [comment]
PR for enabling importas linter: https://github.com/kanisterio/kanister/pull/2239
PR for enabling nakedret linter: https://github.com/kanisterio/kanister/pull/2238

For some linters, a lot of changes are required along with dedicated testing of workflows:
- `stylecheck`
- `funlen`

Adding few more linters to the list that can be enabled:
- funlen
- stylecheck
- gci
- revive
- dogsled
- gochecknoinits
- goconst
- godot
- goimports
- gomnd
- gomodguard
- goprintffuncname
- gosec
- gosimple
- nestif
- nolintlint
- testpackage
- unconvert
- wsl
