### ISSUE TITLE
`ScaleWorkload` should accept labels and should be able to work on those workloads

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#2181]
**Describe the solution you'd like**

I would be helpful if `ScaleWorkload` function can accept the label and then work on the workloads that match specified labels.

**Describe alternatives you've considered**
If there are `n` workload that needs to be scaled down/up, users have tried to have `n` phases to handle them.

**Additional context**
https://kanisterio.slack.com/archives/C85C8V22J/p1689610771625539?thread_ts=1688550937.188959&cid=C85C8V22J

**Comment by muffl0n** [comment]
One thing to consider: when scaling down, we need to save how many replicas are currently running. Otherwise, we would not know to what we should scale up afterwards.

So the replica count should be saved and later be used for scaleup.

**Comment by viveksinghggits** [comment]
I agree. We even have some blueprint example, I think, where we do this already. [This is](https://github.com/kanisterio/kanister/blob/master/examples/cassandra/cassandra-blueprint.yaml#L116) can example.

**Comment by viveksinghggits** [comment]
After the new enhancements in the `ScaleWorkload` function, we now set the original replica count of the workload as output artifact of the function.
If we try to incorporate this ask, and let's assume the we want to scale 3 workloads and all of them have diff original replica count, which replica count should be set as output artifact of the function?

**Comment by muffl0n** [comment]
The only solution I can think of is to output a map with a combination of namespace, workload type and name as well as the count.
As this feels pretty cumbersome maybe this idea should be discarded. 🤔

**Comment by viveksinghggits** [comment]
> As this feels pretty cumbersome maybe this idea should be discarded
I agree.
I think it would be a good idea of have separate phases for diff workloads.
