### ISSUE TITLE
[Image Vulnerability] Vulnerabilities Found in "kafka-adobe-s3-sink-connector" Image (Example image)

### ISSUE THREAD

**Issue by mellon-collie** [kanisterio/kanister#2186]
#  Container Image Vulnerability Report

The container vulnerability scanning GitHub action has found 269 vulnerabilities of High and Critical severity with fixes available for the `kafka-adobe-s3-sink-connector` container image.

## Image

[ghcr.io/kanisterio/kafka-adobe-s3-sink-connector ](https://github.com/kanisterio/kanister/pkgs/container/kafka-adobe-s3-sink-connector)

## Tested Version

v9.99.9-dev

## Details

The detailed report can be found [here](https://github.com/kanisterio/kanister/actions/runs/5511627332/jobs/10047431020).

**Comment by hairyhum** [comment]
Upstream images still have vulnerabilities

**Comment by hairyhum** [comment]
Wont-fix: upstream image is not keeping up to date. The image should only be used in examples.
