### ISSUE TITLE
[Image Vulnerability] High/Critical Severity Vulnerabilities Found in "postgresql" Image

### ISSUE THREAD

**Issue by mellon-collie** [kanisterio/kanister#2209]
#  Container Image Vulnerability Report

The container vulnerability scanning GitHub action has found 5 vulnerabilities of High and Critical severity with fixes available for the `postgresql` container image.

## Image

[ghcr.io/kanisterio/postgresql](https://github.com/kanisterio/kanister/pkgs/container/postgresql)

## Tested Version

v9.99.9-dev

## Details

The detailed report can be found [here](https://github.com/kanisterio/kanister/actions/runs/5511627332/job/14921333403).

**Comment by hairyhum** [comment]
Recent runs didn't have issue with this particular image https://github.com/kanisterio/kanister/actions/runs/7105951856/job/19344328974
