### ISSUE TITLE
[Image Vulnerability] Vulnerabilities Found in "cassandra" Image (Example image)

### ISSUE THREAD

**Issue by mellon-collie** [kanisterio/kanister#2210]
#  Container Image Vulnerability Report

The container vulnerability scanning GitHub action has found 169 vulnerabilities of High and Critical severity with fixes available for the `cassandra` container image.

## Image

[ghcr.io/kanisterio/cassandra ](https://github.com/kanisterio/kanister/pkgs/container/cassandra)

## Tested Version

v9.99.9-dev

## Details

The detailed report can be found [here](https://github.com/kanisterio/kanister/actions/runs/5511627332/job/14921333569).

**Comment by hairyhum** [comment]
Upstream images still have vulnerabilities

**Comment by hairyhum** [comment]
https://github.com/kanisterio/kanister/actions/runs/9233654378/job/25406350441

**Comment by hairyhum** [comment]
Need to check after https://github.com/kanisterio/kanister/pull/3042
