### ISSUE TITLE
[Image Vulnerability] Vulnerabilities Found in "mssql-tools" Image (Example image)

### ISSUE THREAD

**Issue by mellon-collie** [kanisterio/kanister#2216]
#  Container Image Vulnerability Report

The container vulnerability scanning GitHub action has found 17 vulnerabilities of High and Critical severity with fixes available for the `mssql-tools` container image.

## Image

[ghcr.io/kanisterio/mssql-tools](https://github.com/kanisterio/kanister/pkgs/container/mssql-tools)

## Tested Version

v9.99.9-dev

## Details

The detailed report can be found [here](https://github.com/kanisterio/kanister/actions/runs/5511627332/job/14921334848).

**Comment by hairyhum** [comment]
Upstream images still have vulnerability

**Comment by hairyhum** [comment]
Wont fix: base image it too old and is not being updated. The tools image should only be used in examples.
