### ISSUE TITLE
Improve Logs for Repository server Controller

### ISSUE THREAD

**Issue by akankshakumari393** [kanisterio/kanister#2251]
**Describe the bug**
Improve logs wherever applicable, Discussion [https://github.com/kanisterio/kanister/pull/2169#discussion_r1285560793](https://github.com/kanisterio/kanister/pull/2169#discussion_r1285560793)

**Comment by prakrit55** [comment]
hello @akankshakumari393, I want to give it a try... to be precise what do you mean by improving the logs
