### ISSUE TITLE
Dynamic Naming of Actionsets using kanctl

### ISSUE THREAD

**Issue by GeekYiwen** [kanisterio/kanister#2285]
**Describe the solution you'd like**
The `kanctl` Tool should be able to allow dynamic naming. At the moment 'kanctl' always sets the 'generateName: ' field in the metadata of the Actionset to the value of 'backup-'. This results in an Actionset having a generated name with `backup-#####`. Ideally, there should be a way to change the value of the generateName field for example by using a flag like `--name {NAME}`.

**Describe alternatives you've considered**
- Dynamic Naming using the CLI
- Generated Name using other information like name of application, time/date of backup, ... e.g. backup-postgres-2023-01-01-23-59

**Comment by muffl0n** [comment]
Also, it would be nice if one could add arbitrary labels. Currently we are creating the actionset the way we want by calling `kanctl` with `--dry-run` and manipulating the yaml with `yq` before applying it with `kubectl`.

**Comment by viveksinghggits** [comment]
@GeekYiwen I just created the PR that should fix the main problem.
@muffl0n should we create another issue for the labels? I can create one.
