### ISSUE TITLE
Update golangci-linter to the latest release v1.54.0

### ISSUE THREAD

**Issue by mabhi** [kanisterio/kanister#2408]
**Is your feature request related to a problem? Please describe.**
At present kanister is using an updated golang version 1.21.3, and the golangci-linter also needs to be updated to the latest release.
This would ensure to get the latest linter reports and violations.

**Describe the solution you'd like**
`Kanister` build needs to be compatible with latest golangci-linter release.

**Describe alternatives you've considered**
I tried with the version `1.51.2` and it is compatible with the `kanister` build built with golang version `1.21.3` 

**Environment**
Kubernetes Version/Provider: ... AKS
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.27.3

Cluster Size (#nodes): ... 3

**Comment by hairyhum** [comment]
Addressed in https://github.com/kanisterio/kanister/pull/2539
