### ISSUE TITLE
Add CopyVolumeDataAll and PrepareDataAll functions

### ISSUE THREAD

**Issue by laurentiusoica** [kanisterio/kanister#2445]
For datastores with multiple replicas, having the "All" alternatives for CopyVolumeData and PrepareData is useful in order to:

- avoid phase duplication for each of the replicas
- address use cases where the number of replicas for the datastore can change in Day 2. Without the "All" alternative, a blueprint update is required with each scale
- have a single blueprint regardless of the setup of the datastore in various environments

**Comment by mlavi** [comment]
As discussed in Kanister Slack, will defer until Kopia work lands in Kanister.
