### ISSUE TITLE
Broken link in example's README

### ISSUE THREAD

**Issue by ShivangShandilya** [kanisterio/kanister#2496]
**Describe the bug**
When trying to check instructions via provided Kanister Documentation link, it redirects to a broken page.

**To Reproduce**
1. Go to 'examples/README.md'
2. Click on 'Kanister Documentation'
3. See error

**Expected behavior**
The link should redirected to the correct Kanister Documentation page

**Screenshots**
![Screenshot from 2023-11-24 22-14-51](https://github.com/kanisterio/kanister/assets/101946115/633656c4-8105-4d0e-a7de-a5f0b1abdc04)

**Comment by ShivangShandilya** [comment]
I would like to resolve this issue ASAP

**Comment by viveksinghggits** [comment]
> I would like to resolve this issue ASAP

@ShivangShandilya what about this one https://github.com/kanisterio/kanister/issues/1560#issuecomment-1825913549

**Comment by ShivangShandilya** [comment]
Will finish up that one and this today itself, sorry for taking so long been busy with some stuff :frowning:
