### ISSUE TITLE
[BUG] "Split lines failed: bufio.Scanner: token too long" for phase with a lot of output

### ISSUE THREAD

**Issue by muffl0n** [kanisterio/kanister#2612]
**Describe the bug**
One of our phases increased its output by a huge amount of lines from one day to another.
From 450 lines (40Kb) to 2530 lines (169Kb). This caused Kanister to fail the actionset with the error
```
Split lines failed: bufio.Scanner: token too long
```
https://github.com/kanisterio/kanister/blame/master/pkg/output/stream.go#L50

**To Reproduce**
1. Create blueprint
2. Add phase that produces a lot of output: more than 64Kb
3. Run actionset

**Expected behavior**
Output is parsed.

**Screenshots**
n/a

**Environment**
Kubernetes Version/Provider: v1.27.7-gke.1121001
Storage Provider: n/a
Cluster Size (#nodes): n/a
Data Size: n/a
Kanister: 0.99.0

**Additional context**
The default buffer of `bufio` is 64Kb: https://pkg.go.dev/bufio#pkg-constants
That explains, why the error occurs when crossing this boundary.
```
const (
	// MaxScanTokenSize is the maximum size used to buffer a token
	// unless the user provides an explicit buffer with Scanner.Buffer.
	// The actual maximum token size may be smaller as the buffer
	// may need to include, for instance, a newline.
	MaxScanTokenSize = 64 * 1024
)
```

I'm not quite sure how to handle this. Just increasing the buffer blindly to some higher value does not seem like a good solution.

Thread in Slack: https://kanisterio.slack.com/archives/C85C8V22J/p1705490134135299

**Comment by hairyhum** [comment]
@muffl0n thanks for the contribution! 

I think it should be addressable by replacing `bufio.Scanner. with `bufio.Reader` and using `ReadString`, so should be an easy fix.
