### ISSUE TITLE
Is there a non Helm mySQL example?

### ISSUE THREAD

**Issue by elg0ch0** [kanisterio/kanister#262]
Anyone can provide a non Helm mySQL example?

thx

**Comment by tdmanv** [comment]
HI @elg0ch0. 

There is currently an open PR may be close to what you're looking for: https://github.com/kanisterio/kanister/pull/244

Though the readme describes installing MySQL via helm, the Blueprint is not tied to helm. The Blueprint may requiring some tweaks depending on how you deploy MySQL. For example, you may need to change how the secret is referenced, or change `Deployment` to `StatefulSet`. 

If you'd like, I can take a a look at your API object yamls and figure out if the Blueprint will work. Also feel free to join the slack channel: https://kasten.typeform.com/to/QBcw8T
