### ISSUE TITLE
KubeExec should use a default container name when possible

### ISSUE THREAD

**Issue by tdmanv** [kanisterio/kanister#268]
The logic should be the same as `kubectl logs`

**Comment by PrasadG193** [comment]
@tdmanv Could you please add more info?
Do we want to make the `container` field for `KubeExec` function optional and use default container if name not specified?

**Comment by ihcsim** [comment]
See https://pkg.go.dev/k8s.io/kubectl/pkg/cmd/util/podcmd#FindOrDefaultContainerByName.

**Comment by pavannd1** [comment]
Reactivate
