### ISSUE TITLE
Fix Tutorial docs to work with current s3

### ISSUE THREAD

**Issue by stand-sure** [kanisterio/kanister#2779]
**Is your feature request related to a problem? Please describe.**

https://github.com/kanisterio/kanister/blob/master/docs/tutorial.rst uses containerlabs/aws-sdk which is 7 years old and does **not** support regions and does not support S3v4.

This causes the tutorial examples to fail.

**Describe the solution you'd like**

Replace `image: containerlabs/aws-sdk`
With `image: amazon/aws-cli`

**Comment by shuguet** [comment]
Hello @stand-sure,

Thank you for noticing and reporting this!

Let me update the Deployment spec to reflect that change now, I'll open a PR.
