### ISSUE TITLE
Kanister functions should have a way to configure ImagePullPolicy

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#283]
As of now, there is no way to set imagePullPolicy for Kanister functions like KubeTasks or PrepareData where we need to mention container image. The imagePullPolicy is set as "Always" by default. It would save a lot of time if we can configure this especially when the image size is considerably large.

**Comment by tdmanv** [comment]
Closing this in favor of https://github.com/kanisterio/kanister/issues/289
