### ISSUE TITLE
Document using labels to enhance kanister logs context

### ISSUE THREAD

**Issue by hairyhum** [kanisterio/kanister#2873]
Currently kanister controller includes actionset labels with prefix `kanister.io/` into controller logs when logging events for actionsets. https://github.com/kanisterio/kanister/blob/master/pkg/controller/controller.go#L391

This is not documented anywhere at the moment. Would be nice addition to something like https://docs.kanister.io/tasks.html

**NOTE** As we move towards the new docs format, docs changes should be repeated in `docs` and `docs_new` directories.

**Comment by viveksinghggits** [comment]
Looks good to me, while documenting we can also mention some use cases.
