### ISSUE TITLE
examples/mongo-sidecar/backup-actionset.yaml is missing name

### ISSUE THREAD

**Issue by tamalsaha** [kanisterio/kanister#30]
I was trying instructions from https://docs.kanister.io/#getting-started . I got this error:

```
$ kubectl apply -f examples/mongo-sidecar/backup-actionset.yaml
error: error when retrieving current configuration of:
&{0xc4214132c0 0xc422206e70 default  examples/mongo-sidecar/backup-actionset.yaml 0xc421fe6b28 0xc421fe6b28  false}
from server for: "examples/mongo-sidecar/backup-actionset.yaml": resource name may not be empty
```

**Comment by vkamra** [comment]
@tamalsaha - I believe it's related to the usage of `generateName` in the yaml spec not being compatible with `apply -f`. Try `kubectl create -f examples/mongo-sidecar/backup-actionset.yaml`

https://github.com/kanisterio/kanister/tree/master/examples/mongo-sidecar has the right command - I'll push a PR to update the docs to reflect this.

**Comment by ntolia** [comment]
Addressed by a commit that just went in.
