### ISSUE TITLE
Kando can't process documented profile schema

### ISSUE THREAD

**Issue by gouglhupf** [kanisterio/kanister#328]
When running `kando` in the version 0.21.0 it can't read the profile in the documented schema.
Error message:
```
ERRO[0000] json: cannot unmarshal object into Go struct field KeyPair.Secret of type string
failed to unmarshal profile
github.com/kanisterio/kanister/pkg/kando.unmarshalProfileFlag
        /go/src/github.com/kanisterio/kanister/pkg/kando/location.go:53
github.com/kanisterio/kanister/pkg/kando.runLocationPush
        /go/src/github.com/kanisterio/kanister/pkg/kando/location_push.go:48
github.com/kanisterio/kanister/pkg/kando.newLocationPushCommand.func1
        /go/src/github.com/kanisterio/kanister/pkg/kando/location_push.go:36
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/kanisterio/kanister/pkg/kando.Execute
        /go/src/github.com/kanisterio/kanister/pkg/kando/kando.go:31
main.main
        /go/src/github.com/kanisterio/kanister/cmd/kando/main.go:22
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```
The JSON I try to call `kando` with:
```json
{
    "apiVersion": "cr.kanister.io/v1alpha1",
    "credential": {
        "keyPair": {
            "ID": "access_key_id",
            "secret": {
                "apiVersion": "v1",
                "name": "default-profile-creds",
                "namespace": "kanister"
            },
            "secretField": "secret_access_key"
        },
        "type": "keyPair"
    },
    "kind": "Profile",
    "location": {
        "bucket": "my_bucket",
        "endpoint": "https://example.com",
        "prefix": null,
        "region": null,
        "type": "s3Compliant"
    },
    "metadata": {
        "labels": {
            "app": "profile",
            "chart": "profile-0.20.0",
            "heritage": "Tiller",
            "release": "kanister-default-profile"
        },
        "name": "default-profile",
        "namespace": "kanister"
    },
    "skipSSLVerify": false
}
```

Then I modify the JSON to the following it works:

```json
{
    "apiVersion": "cr.kanister.io/v1alpha1",
    "credential": {
        "keyPair": {
            "id": "xxxxxxxxx",
            "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        },
        "type": "keyPair"
    },
    "kind": "Profile",
    "location": {
        "bucket": "my_bucket",
        "endpoint": "https://example.com",
        "prefix": null,
        "region": null,
        "type": "s3Compliant"
    },
    "metadata": {
        "labels": {
            "app": "profile",
            "chart": "profile-0.20.0",
            "heritage": "Tiller",
            "release": "kanister-default-profile"
        },
        "name": "default-profile",
        "namespace": "kanister"
    },
    "skipSSLVerify": false
}
```

The JSON for the Kubernetes resource that is not working was created by the [helm chart "Profile CustomResource"](https://github.com/kanisterio/kanister/tree/master/helm/profile) contained in the repository.

### Software Versions
Kanister 0.21.0
Kubernetes 1.14.6

**Comment by SupriyaKasten** [comment]
When we execute `kando` command from within a blueprint, we pass the value of Profile generate by TemplateParams (check this file https://github.com/kanisterio/kanister/blob/master/pkg/param/param.go#L84) after converting it to JSON. So while executing the `kando` command on terminal, we cannot convert the `profile.cr.kanister.io` into json and pass it to `kando`. Hence, it failed in your case. 

However a simple example of how you can execute `kando` on terminal is as follows:
```
echo "hello" | kando location push --profile '{"Location":{"type":"s3Compliant","bucket":"MY_TEST_BUCKET","endpoint":"","prefix":"","region":""},"Credential":{"Type":"keyPair","KeyPair":{"ID":"MY_AWS_ACCESS_KEY_ID","Secret":"MY_AWS_SECRET_ACCESS_KEY"}},"SkipSSLVerify":false}' --path /test.txt -
```
The above command will push file test.txt, with content "hello", to `MY_TEST_BUCKET ` in S3. WE have converted `TemplateParams.Profile` into JSON and passed it to `kando`

Please take a look at this example blueprint https://github.com/kanisterio/kanister/blob/master/examples/helm/kanister/kanister-mongodb-replicaset/kanister/mongodb-blueprint.yaml which uses `kando` to backup, restore and delete data. 

Hope this resolves your issue :) 
Let us know if we can be of any further help.

**Comment by gouglhupf** [comment]
Thank you for the reply.
I didn't realize the JSON passed to `kando` is not the same JSON that you get from the Kubernetes API. Therefore, my conclusion for the error was wrong.
The issue in my blueprint was that I didn't put the function `toJson` in front of the `.Profile` as in the example https://github.com/kanisterio/kanister/blob/master/examples/helm/kanister/kanister-mongodb-replicaset/kanister/mongodb-blueprint.yaml#L31. The dedicated documentation https://docs.kanister.io/tooling.html#kando does not include the function `toJson` in the example. Maybe the documentation needs to be updated.

**Comment by SupriyaKasten** [comment]
Thanks for notifying  us about the issue. We have updated the docs in PR https://github.com/kanisterio/kanister/pull/331.
Closing this issue.
