### ISSUE TITLE
Sample blueprint to snapshot/restore AWS RDS database instances

### ISSUE THREAD

**Issue by vkamra** [kanisterio/kanister#329]
We should implement a sample blueprint that leverages the AWS API to snapshot/restore AWS RDS databases.

K8s applications that use a managed service such as RDS will typically create a ConfigMap with the relevant configuration (e.g. see https://github.com/kastenhq/pgtest).

This task tracks implementing a blueprint that uses the AWS snapshot/restore functionality would demonstrate how users can leverage Kanister with such applications.

**Comment by PrasadG193** [comment]
@tdmanv can we close this?

**Comment by tdmanv** [comment]
Thanks @PrasadG193 !
