### ISSUE TITLE
Has anyone tried this with OpenShift?

### ISSUE THREAD

**Issue by alberttwong** [kanisterio/kanister#37]
Just curious....

**Comment by tdmanv** [comment]
Hi @alberttwong 
I have not personally tested this with OpenShift, but it's definitely on my roadmap.

Right now our CI pipeline runs in minikube, but I was thinking of setting up an Openshift Online starter cluster and run the tests there instead. 

Can I ask what your use case for kanister is?

**Comment by tdmanv** [comment]
Just got word that @depohmel has tried kanister with Openshift. We do expect it to work with Openshift, but if you experience any bugs, do let us know.
