### ISSUE TITLE
[BUG] installing kanctl results in an error

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#380]
**Describe the bug**
Running the command `$ go install -v github.com/kanisterio/kanister/cmd/kanctl` to install `kanctl` results in below error message 
```
go: github.com/kanisterio/kanister@v0.0.0-20191101190213-91a332a6d477 requires
	github.com/graymeta/stow@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**To Reproduce**
Just try to install `kanctl` using command `go install -v github.com/kanisterio/kanister/cmd/kanctl`.

**Expected behavior**
`kanctl` should be installed correctly.

**Additional context**
If I run `go install -v github.com/kanisterio/kanister/cmd/kanctl` after cloning the kanister repo and it seems to be working fine.

I have below go version installed on my machine 
```
go version go1.13.4 linux/amd64
```

**Comment by pavannd1** [comment]
@viveksinghggits Thanks for opening this issue.
I will push a fix to the docs. 
Meanwhile, please try running the following command to install both `kanctl` and `kando`.
```
curl https://raw.githubusercontent.com/kanisterio/kanister/master/scripts/get.sh | bash -s "0.20.0"
```

**Comment by pavannd1** [comment]
Updated the docs with correct command.
