### ISSUE TITLE
Update links to "Community Applications" in README to point to "examples/stable"

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#409]
**Is your feature request related to a problem? Please describe.**
Currently, example listed on README https://github.com/kanisterio/kanister#community-applications are pointing to the outdated example repos

**Describe the solution you'd like**
We should be pointing it to the applications under `examples/stable` dir

**Comment by rahulsidgondapatil** [comment]
I am working on updating the links of example repos. Will create a PR shortly.
