### ISSUE TITLE
Refactor codebase to use helm3

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#410]
**Is your feature request related to a problem? Please describe.**
We should be refactoring codebase to use helm3 in build and test script

Higher-level changes we need to do:
- Remove `make tiller` target (since helm 3 is tillerless)
- Use helm3 in travis CI
- Refactor `release_helm.sh`
- Add a step in installer docs to create namespace before installing charts since helm3 doesn't create ns if not present (https://docs.kanister.io/install.html#deploying-via-helm)

**Comment by PrasadG193** [comment]
@ankitjain235 is this being tracked in helm chart upgrade task you are doing?

**Comment by ankitjain235** [comment]
@PrasadG193 Currently, I am removing stable chart dependencies. Will be handling this as part of removing helm2 dependencies. This is also a part of the same task.
