### ISSUE TITLE
Add foundationDB in integration test suite

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#452]
We should have [foundationDB](https://www.foundationdb.org/) in our integration test suite along with the other applications that we support right now.
To install `foundationDB` we can use the [operator](https://github.com/foundationdb/fdb-kubernetes-operator) that they have just open sourced. 
## Challenges
But the problem with this operator is that it doesn't have the utilities (`fdbbackup`, `fdbrestore` and `backup_agent`) to support backup and restore, this issue is discussed [here](https://forums.foundationdb.org/t/regarding-issue-faced-while-running-fdbbackup/1458/7?u=viveksinghggits).

Without having the `backup_agent` utility running we will have to [manually change the fdbmonitor configuration file](https://forums.foundationdb.org/t/regarding-issue-faced-while-running-fdbbackup/1458/6?u=viveksinghggits) to start the `backup_agent` and after doing that we are successfully able to take the backup but restoring that backup results in an error and we are trying to get in touch with the foundationDB operator team to [discuss](https://forums.foundationdb.org/t/restoring-a-completed-backup-version-results-in-an-error/1845) what can be done about that.

I have also raised an issue in their github repo to support the backup and restore if the cluster is installed using operator
https://github.com/FoundationDB/fdb-kubernetes-operator/issues/46.

**Comment by tdmanv** [comment]
closed in https://github.com/kanisterio/kanister/pull/467
