### ISSUE TITLE
Add more information to `kubectl describe actionset`

### ISSUE THREAD

**Issue by abhide** [kanisterio/kanister#49]
Add more information regarding the time taken by each phase and outcome of actionset.

It would be great if 'kubectl get actionset -owide' displays outcome and time taken to completion for an actionset.

**Comment by ntolia** [comment]
@SupriyaKasten Do you recent patches address this? If not, what is left?

**Comment by SupriyaKasten** [comment]
It displays the outcome of actionset, also displays the age and description of a phase but not the time taken by a phase to complete, we can calculate that from the age for now.
