### ISSUE TITLE
Support for Openshift's DeploymentConfigs

### ISSUE THREAD

**Issue by tdmanv** [kanisterio/kanister#501]
Many Openshift clusters still use DeploymentConfigs.

We should make DeploymentConfigs a first class object in Kanister. This means:

* kanctl flags for DeploymentConfigs
* Add a to https://github.com/kanisterio/kanister/blob/master/pkg/param/param.go#L38 and support rendering
* Add an integration test app 
* Update docs

**Comment by viveksinghggits** [comment]
All the raise PR related to this issue have been merged, closing the issue.
