### ISSUE TITLE
[BUG] RestoreRDSSnapshot function does not restore partially corrupted table 

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#505]
**Describe the bug**

When postgres db is restored with RestoreRDSSnapshot function from dump, it works perfectly if a table in a database is completely empty. If few rows are already present in the table to be restored, it skips the table. 

**To Reproduce**
1. Create RDS posgres instance, add a table and rows
2. Take dump backup using CreateRDSSnapshot and ExportRDSSnapshotToLocation function
3. Remove few rows from the table
4. Restore from dump by with RestoreRDSSnapshot function (setting snapshotID=nil in BP)
5. Verify if all table rows are restored

**Expected behavior**
DB table should contain all the rows from backup after restore

**Comment by viveksinghggits** [comment]
We should make note of one other thing here is that, while adding applications in the integration test suite, while resetting the application we are dropping the database most of the times. We have not tested those for partial restore, as well.
We might need to  re-iterate that.
