### ISSUE TITLE
[BUG] Uninstalling an app in Kanister test suite should also delete the created CRDs

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#566]
**Describe the bug**
In Kanister test suite, if an application is creating the CRD, that CRD should be deleted when we uninstall the application. This is not happening as of now, and because of that if we re run the test, the tests would fail because the CRD would already be there in the cluster.

**To Reproduce**
1. Run the Kanister test suite for app foundationdb locally
2. Test should pass
3. Run the same test again.
4. Now we will get an error saying ` Error: rendered manifests contain a resource that already exists.`

**Expected behavior**
The test should run successfully even the second time.

**Screenshots**
NA

**Additional context**
To resolve this we can either try to delete the created CRDs in the application un install or we can check if that should be a the part of helm uninstall.

**Comment by A-kanksh-a** [comment]
@viveksinghggits 
This issue persists only with FoundationDB and not other kanister applications. For Example, if we run the Couchbase application twice which also creates some CRDs, It would pass.
