### ISSUE TITLE
kanctl profile create fails with OCP 4.3 on AWS

### ISSUE THREAD

**Issue by screeley44** [kanisterio/kanister#590]
**Describe the bug**
When executing the profile command:

```
kanctl create profile s3compliant --bucket <bucket name> --access-key <AWS_SECRET_ACCESS_KEY> --secret-key <AWS_SECRET_ACCESS_KEY> --region <region> --namespace kanister
```

Get error:
```
secret 's3-secret-4p6exs' created
Failed the 'Validate bucket region specified in profile' check.. ❌
validation failed, deleting secret 's3-secret-4p6exs'
secret 's3-secret-4p6exs' deleted
Error: profile validation failed: NotFound: Not Found
	status code: 404, request id: 894C42BE4D12564C, host id: AUTiFOkcBPmIVs1TVVwc5xkJSBx2cYtROmpMDlcaswKBw1MLjm+B8EjCKNeDaIrjgHIAfkEfqWk=
ERRO[2020-02-27T17:29:34.983717278Z] profile validation failed: NotFound: Not Found
	status code: 404, request id: 894C42BE4D12564C, host id: AUTiFOkcBPmIVs1TVVwc5xkJSBx2cYtROmpMDlcaswKBw1MLjm+B8EjCKNeDaIrjgHIAfkEfqWk=  File=cmd/kanctl/main.go Function=main.main Line=28 hostname=ip-10-0-1-159.ec2.internal
```

**To Reproduce**
1. Run above command from AWS instance (acting as OCP 4.3 client)

**Expected behavior**
profile validation succeeds and both secrets are created

**Additional Context**
Using Openshift and MySQL example from kanister repo

**Comment by tdmanv** [comment]
Hi @screeley44 thank you for filing the bug.

A few questions:
* Is this using s3 or an s3 compliant object storage?
For non s3 buckets that are s3 compliant, you'll also need to specify the endpoint?

* Does the bucket's region match the region you've specified?
You might see this error if the'ere a region mismatch

**Comment by screeley44** [comment]
@tdmanv - thanks for the reply, so I'm using AWS S3 for my object store and your second question makes me think now that maybe I misunderstood or missed in the docs that a bucket needs to exist and I need to create the bucket myself before I can create the profile. I was under the impression that this command also provisioned the bucket. Is this the case that I should have created the bucket before I run the command?

**Comment by tdmanv** [comment]
Thanks for the response.

I'll double check, but I believe kanctl will create the bucket in that region if it doesn't exist. If it does exist it checks that the bucket exists in that region

**Comment by screeley44** [comment]
update - if I create the bucket first, the command works... @tdmanv
