### ISSUE TITLE
[BUG] kanctl resource validation is buggy for native resources if they are being provided as --objects 

### ISSUE THREAD

**Issue by viveksinghggits** [kanisterio/kanister#631]
**Describe the bug**
If we want to give pod as subject while creating the actionset the validation of that pod fails stating couldn't find the resource. But if we create the yaml using `--dry-run` flag and then create the actionset using `kubectl create -f` things work, it means the resource validation has some issues and we should resolve that.  

**To Reproduce**
Try to create an actionset and give a pod details using --object flag
```
... --object api/v1/pods/podnamespace/podname
```

**Expected behavior**
The actionset should be created successfully if `podname` is there in the `podnamespace` the , but it is not getting created stating 
resource `podname` not found in `podnamespace`.

**Screenshots**

**Additional context**

**Comment by viveksinghggits** [comment]
A PR has been raised https://github.com/kanisterio/kanister/pull/638
Here is how we can provide the pod now.
```
kanctl create actionset \
--action backup \
--namespace kanister \
--blueprint etcd-blueprint \
--objects /v1/pods/kube-system/etcd-minikube \
--profile kube-system/s3-profile-xhgl9
```

**Comment by PrasadG193** [comment]
@viveksinghggits Can this be closed?

**Comment by viveksinghggits** [comment]
Yes. Fixed in 
https://github.com/kanisterio/kanister/pull/638
