### ISSUE TITLE
Add support to make phase always run

### ISSUE THREAD

**Issue by PrasadG193** [kanisterio/kanister#674]
**Is your feature request related to a problem? Please describe.**

Consider we have a BP where we are trying to perform backup in multiple phases. And we have last phase (say cleanup phase) which cleans up temporary artifacts that are created as a part of backup. Even If any of the phase fails, the cleanup phase should get called. So there should be a way to mark cleanup phase run always.

**Describe the solution you'd like**
We can add a field to `phase` spec (e.g `alwaysRun=true/false`) to toggle the behaviour

**Comment by vkamra** [comment]
@PrasadG193 - this would be useful - a section in the phase where we would specify this and perhaps other _execution controls_ such as phase timeouts, retries would be a good place to put this. I know @tdmanv has discussed this.

**Comment by ihcsim** [comment]
Fixed by https://github.com/kanisterio/kanister/pull/1297.
