### ISSUE TITLE
[BUG] Slow start of controller container

### ISSUE THREAD

**Issue by ghost** [kanisterio/kanister#720]
**Describe the bug**
Currently, we have a problem where the controller takes quite sometime to be ready for executing new ActionSets. The controller pod is marked as ready but it will not execute new ActionSets. During this time it seems to loop over every existing ActionSets and prints the message:

```
time="2020-07-20T14:13:11.780775445Z" level=error msg="Cannot initialize non-nil ActionSet Status" ActionSet=xxxxxx-d2cj4 File=pkg/controller/controller.go Function="github.com/kanisterio/kanister/pkg/controller.(*Controller).onAddActionSet" Line=200 cluster_name=xxxxxx hostname=xxxxxx
```

Our clusters have different amounts of ActionSets but one cluster has 8098 ActionSets and the start time is 36 min.

**To Reproduce**
1. Create a lot of ActionSets
2. Restart or recreate controller
3. Immediately create a new ActionSets
4. After too much time the ActionSet gets executed

**Expected behavior**
I would be great if the startup could be speed up and less verbose.

**Screenshots**

-no screenshots-

**Additional context**

-no additional context-

**Comment by tdmanv** [comment]
@digitalmobil-leiner thank you for filing this. 8k is a lot of ActionSets. Do you know the reason why there are so many in your cluster? Are they all referencing useful artifacts?

Please elaborate your use case a bit and we help with a workaround or a fix.

Thank you,
Tom

**Comment by digitalmobil-leiner** [comment]
Hello,

Thanks for the reply and your time. First we use "kanister" for backups and data transfer (production data to some development environment). The cluster in question has many small instances of our application. Each has its own data (a database and block storage), so the ActionSet has two artifacts a path and id for the file backup and a path for the database dump. We keep the backups separate to keep restores easy and as atomic as possible. The cluster has current 39 cron jobs. Each creates one ActionSet every night. Additionally, on every deploy to a production environment an ActionSet is created.

We are currently trying to reduce the number of ActionSets we have stored by keeping backups for less time and cleaning up failed ActionSets or ActionSets which do not have any artifacts. With the current number of applications we run we can probably reduce the number of ActionSets by about 40%. But by the end of the year will have about 60 cron jobs creating backups every night. That would still result in about 6000 ActionSets.

**Comment by tdmanv** [comment]
That's certainly a challenging use case. I'll check if updating the Kubernetes Informer library used by Kanister would help. In the short term, I suggest storing the ActionSets off cluster and deleting them from your production cluster.

We also have a commercial product that would help manage all that for you, which has a free edition. I'd be happy to organize a demo in you're interested. Please mail tom@kasten.io and I can set something up.

**Comment by tdmanv** [comment]
@digitalmobil-leiner could you please also give me some information on your cluster? What version of kubernetes are you using? Are you in a cloud provider? How many nodes are in your clusters and how many clusters?
