### ISSUE TITLE
[BUG] rds-postgres-snap-blueprint does not consider region of DB instance when triggering the snapshot

### ISSUE THREAD

**Issue by 617m4rc** [kanisterio/kanister#783]
**Describe the bug**

The blueprint tries to create the database instance snapshot in the wrong region. Apparently, it is either not providing any region information at all, or it using the region specified in the location profile, which is not necessarily the right one. 

**To Reproduce**
1. Create an RDS instance in region eu-west-1.
2. Create an S3 bucket in region eu-central-1 and use that bucket in the location profile.

any backup action for the RDS database fails with error message

`Failed to create snapshot: DBInstanceNotFound: DBInstance not found: xxx status code: 404, ...
`

When checking AWS CloudTrail, one can see that the request ended up in the wrong region.

`{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "XXX",
        "arn": "arn:aws:iam::XXX:user/XXX",
        "accountId": "XXX",
        "accessKeyId": "XXX",
        "userName": "XXX"
    },
    "eventTime": "2020-09-29T11:58:26Z",
    "eventSource": "rds.amazonaws.com",
    "eventName": "CreateDBSnapshot",
    **"awsRegion": "eu-central-1",**
    "sourceIPAddress": "XXX",
    "userAgent": "aws-sdk-go/1.31.6 (go1.14.2; linux; amd64)",
    "errorCode": "DBInstanceNotFoundFault",
    "errorMessage": "DBInstance not found: XXX",
    "requestParameters": {
        "dBSnapshotIdentifier": "XXX",
        "dBInstanceIdentifier": "XXX"
    },
    "responseElements": null,
    "requestID": "fefede1b-5215-4b81-ad53-beddd8895ae8",
    "eventID": "78499c87-3d6a-4ac1-b95e-94cf0bfbf064",
    "eventType": "AwsApiCall",
    "recipientAccountId": "XXX"
}`

**Expected behavior**

API call for snapshot creation considers regions. The region can be specified in the config-map, or is automatically derived from the provided RDS endpoint.

**Environment**
Kubernetes Version/Provider: v1.17.9-eks-4c6976
Cluster Size (#nodes): 3

**Comment by vkamra** [comment]
@617m4rc - thanks for the bug report. We'll take a look.
