### ISSUE TITLE
Helm install of Kanister can't create events

### ISSUE THREAD

**Issue by ashmrtn** [kanisterio/kanister#90]
The current helm chart for kanister grants the kanister-operater SA permissions in the default `edit` permission group which lacks the ability to create events. Giving the SA the default `admin` permission group would most likely resolve this issue. To accomplish this, the user would have to create a second SA for Tiller which would need at least the `admin` permissions. This is required because the kubernetes API [prevents privilege escalation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping) and, by default, Tiller runs with the `default` privilege group which does not have admin rights. Setting up a new SA for Tiller, binding it to the `admin` permission group, and running `helm init ...` should configure the system properly.

[This example](https://github.com/kubernetes/helm/blob/master/docs/rbac.md#example-service-account-with-cluster-admin-role), or any of the following ones should be sufficient to properly configure Tiller.

**Comment by tdmanv** [comment]
This was fixed a while back
