### ISSUE TITLE
postgresql-repmgr support

### ISSUE THREAD

**Issue by jsbrain** [kanisterio/kanister#957]
Hey,

is using `bitnami/postgresql-repmgr` instead of `bitnami/postgresql` for postgres backups already possible or are there any plans to support it? 🙂

**Comment by viveksinghggits** [comment]
Hi @jsbrain,
Did you try using the blueprint that we already have, let's try that and see if that works. 
If you look into that blueprint, I think you would be able to figure out how we are backing up that database.

**Comment by jsbrain** [comment]
I'm currently on it, yes. To my understanding:
I'm using bitnami charts. Do I actually need to specify the image from ghcr.io/kanisterio/postgresql to run the deployment or should I run just the default bitnami postgres deployment and add a postgresql sidecar (I have seen some examples like that on Google) or neither of both?

Sorry to ask probably obvious stuff but I'm a little confused 🤦🏻‍♂️

**Comment by viveksinghggits** [comment]
So the image that we use in blueprint `ghcr.io/kanisterio/postgresql`, just has postgres client to backup the database. you can use another image as well as long as you have postgres client there.
I think it would be better if we continue this on kanister slack.

kanisterio.slack.com

**Comment by jsbrain** [comment]
Ok sure, thanks for the info so far 🙂
