### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pranitha24** [kanisterio/kanister#968]
**Describe the bug**

I have Installed Kasten in my AKS cluster to perform back ups of persistent volumes to test DR case.
After the installation I am able to access the k10 dashboard but getting the error like "**One of the services (dashboardbff-svc) is slow to respond"** 

and also it is not showing applications inside the cluster, please find the screenshot attached.

![image](https://user-images.githubusercontent.com/83630784/116965013-68ea6700-ac9c-11eb-87df-a4117c8cd1f4.png)

![image](https://user-images.githubusercontent.com/83630784/116964892-1a3ccd00-ac9c-11eb-991d-6cbbda522632.png)

**To Reproduce**
1. Go to http://127.0.0.1:8080/k10/#/dashboard 

**Expected behavior**
I am expecting the k10 dashboard to be available with the applications which are deployed in the AKS cluster and able to take backups of PVs.

**Environment**
Kubernetes Version/Provider: 1.19.6
Storage Provider: Azure Blob storage
Cluster Size (#nodes):  4 nodes
Data Size: 5GB

**Comment by viveksinghggits** [comment]
Hey @Pranitha24 ,
This is not the good place to discuss about K10 issues. I would recommend you dropping a mail to k10 support at `support@kasten.io`
